config/routes.rb
Rails.application.routes.draw do
  resources :jobstittles
  resources :magazines
  resources :cenologists
  resources :winestrains
  resources :strains
  resources :wines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cenologist.rb
class Cenologist < ApplicationRecord
end

app/controllers/cenologists_controller.rb
class CenologistsController < ApplicationController
  before_action :set_cenologist, only: %i[ show edit update destroy ]

  # GET /cenologists or /cenologists.json
  def index
    @cenologists = Cenologist.all
  end

  # GET /cenologists/1 or /cenologists/1.json
  def show
  end

  # GET /cenologists/new
  def new
    @cenologist = Cenologist.new
  end

  # GET /cenologists/1/edit
  def edit
  end

  # POST /cenologists or /cenologists.json
  def create
    @cenologist = Cenologist.new(cenologist_params)

    respond_to do |format|
      if @cenologist.save
        format.html { redirect_to cenologist_url(@cenologist), notice: "Cenologist was successfully created." }
        format.json { render :show, status: :created, location: @cenologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cenologists/1 or /cenologists/1.json
  def update
    respond_to do |format|
      if @cenologist.update(cenologist_params)
        format.html { redirect_to cenologist_url(@cenologist), notice: "Cenologist was successfully updated." }
        format.json { render :show, status: :ok, location: @cenologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cenologists/1 or /cenologists/1.json
  def destroy
    @cenologist.destroy

    respond_to do |format|
      format.html { redirect_to cenologists_url, notice: "Cenologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cenologist
      @cenologist = Cenologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cenologist_params
      params.require(:cenologist).permit(:name)
    end
end

app/helpers/cenologists_helper.rb
module CenologistsHelper
end

app/views/cenologists/_cenologist.html.erb
<div id="<%= dom_id cenologist %>">
  <p>
    <strong>Name:</strong>
    <%= cenologist.name %>
  </p>

</div>

app/views/cenologists/_form.html.erb
<%= form_with(model: cenologist) do |form| %>
  <% if cenologist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cenologist.errors.count, "error") %> prohibited this cenologist from being saved:</h2>

      <ul>
        <% cenologist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cenologists/edit.html.erb
<h1>Editing cenologist</h1>

<%= render "form", cenologist: @cenologist %>

<br>

<div>
  <%= link_to "Show this cenologist", @cenologist %> |
  <%= link_to "Back to cenologists", cenologists_path %>
</div>

app/views/cenologists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cenologists</h1>

<div id="cenologists">
  <% @cenologists.each do |cenologist| %>
    <%= render cenologist %>
    <p>
      <%= link_to "Show this cenologist", cenologist %>
    </p>
  <% end %>
</div>

<%= link_to "New cenologist", new_cenologist_path %>

app/views/cenologists/new.html.erb
<h1>New cenologist</h1>

<%= render "form", cenologist: @cenologist %>

<br>

<div>
  <%= link_to "Back to cenologists", cenologists_path %>
</div>

app/views/cenologists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cenologist %>

<div>
  <%= link_to "Edit this cenologist", edit_cenologist_path(@cenologist) %> |
  <%= link_to "Back to cenologists", cenologists_path %>

  <%= button_to "Destroy this cenologist", @cenologist, method: :delete %>
</div>