config/routes.rb
Rails.application.routes.draw do
  resources :jobstittles
  resources :magazines
  resources :cenologists
  resources :winestrains
  resources :strains
  resources :wines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/winestrain.rb
class Winestrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/controllers/winestrains_controller.rb
class WinestrainsController < ApplicationController
  before_action :set_winestrain, only: %i[ show edit update destroy ]

  # GET /winestrains or /winestrains.json
  def index
    @winestrains = Winestrain.all
  end

  # GET /winestrains/1 or /winestrains/1.json
  def show
  end

  # GET /winestrains/new
  def new
    @winestrain = Winestrain.new
  end

  # GET /winestrains/1/edit
  def edit
  end

  # POST /winestrains or /winestrains.json
  def create
    @winestrain = Winestrain.new(winestrain_params)

    respond_to do |format|
      if @winestrain.save
        format.html { redirect_to winestrain_url(@winestrain), notice: "Winestrain was successfully created." }
        format.json { render :show, status: :created, location: @winestrain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @winestrain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /winestrains/1 or /winestrains/1.json
  def update
    respond_to do |format|
      if @winestrain.update(winestrain_params)
        format.html { redirect_to winestrain_url(@winestrain), notice: "Winestrain was successfully updated." }
        format.json { render :show, status: :ok, location: @winestrain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @winestrain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /winestrains/1 or /winestrains/1.json
  def destroy
    @winestrain.destroy

    respond_to do |format|
      format.html { redirect_to winestrains_url, notice: "Winestrain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_winestrain
      @winestrain = Winestrain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def winestrain_params
      params.require(:winestrain).permit(:porcentaje, :wine_id, :strain_id)
    end
end

app/helpers/winestrains_helper.rb
module WinestrainsHelper
end

app/views/winestrains/_form.html.erb
<%= form_with(model: winestrain) do |form| %>
  <% if winestrain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(winestrain.errors.count, "error") %> prohibited this winestrain from being saved:</h2>

      <ul>
        <% winestrain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :porcentaje, style: "display: block" %>
    <%= form.number_field :porcentaje %>
  </div>

  <div>
    <%= form.label :wine_id, style: "display: block" %>
    <%= form.text_field :wine_id %>
  </div>

  <div>
    <%= form.label :strain_id, style: "display: block" %>
    <%= form.text_field :strain_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/winestrains/_winestrain.html.erb
<div id="<%= dom_id winestrain %>">
  <p>
    <strong>Porcentaje:</strong>
    <%= winestrain.porcentaje %>
  </p>

  <p>
    <strong>Wine:</strong>
    <%= winestrain.wine_id %>
  </p>

  <p>
    <strong>Strain:</strong>
    <%= winestrain.strain_id %>
  </p>

</div>

app/views/winestrains/edit.html.erb
<h1>Editing winestrain</h1>

<%= render "form", winestrain: @winestrain %>

<br>

<div>
  <%= link_to "Show this winestrain", @winestrain %> |
  <%= link_to "Back to winestrains", winestrains_path %>
</div>

app/views/winestrains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Winestrains</h1>

<div id="winestrains">
  <% @winestrains.each do |winestrain| %>
    <%= render winestrain %>
    <p>
      <%= link_to "Show this winestrain", winestrain %>
    </p>
  <% end %>
</div>

<%= link_to "New winestrain", new_winestrain_path %>

app/views/winestrains/new.html.erb
<h1>New winestrain</h1>

<%= render "form", winestrain: @winestrain %>

<br>

<div>
  <%= link_to "Back to winestrains", winestrains_path %>
</div>

app/views/winestrains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @winestrain %>

<div>
  <%= link_to "Edit this winestrain", edit_winestrain_path(@winestrain) %> |
  <%= link_to "Back to winestrains", winestrains_path %>

  <%= button_to "Destroy this winestrain", @winestrain, method: :delete %>
</div>